spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.50.179/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.1.20/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
# 空值前端返回不显示
#  jackson:
#    default-property-inclusion: non_null
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: d:/log
#  file: d:/log/sell.log
#  level: debug

server:
  context-path: /sell
#server:
#  port: 80

wechat:
  mpAppId: wx342df2e01b8146e0
  mpAppSecret: 16eb47e1f1985a51e95517ed8db726ae
  openAppId: oF31q08l8rlD-0aWAdeAWMlb4Qbk
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://kydh.mynatapp.cc/sell/pay/notify